/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getHello'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user */
    get: operations['UsersController_getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user */
    post: operations['AuthController_register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login a user */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh access token */
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Clear refreshToken from cookie */
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedule': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get week schedule of current user */
    get: operations['ScheduleController_getUserSchedule'];
    /** Update week schedule of the user */
    put: operations['ScheduleController_updateUserSchedule'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bookings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all slots for a selected date */
    get: operations['BookingsController_getSlots'];
    put?: never;
    /** Create a booking */
    post: operations['BookingsController_createBooking'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bookings/my': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all bookings of a user */
    get: operations['BookingsController_getUserBookings'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bookings/{id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Cancellation of visit */
    patch: operations['BookingsController_cancelBooking'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UserResponseDto: {
      /**
       * @description Unique identifier for the user
       * @example fPT7R2iwCQh9aAyYW7421
       */
      id: string;
      /**
       * @description Email address of the user
       * @example john.doe@example.com
       */
      email: string;
      /**
       * @description Full name of the user
       * @example John Doe
       */
      name: string;
      /**
       * @description Slug for the user
       * @example john_doe
       */
      slug: string;
    };
    SignUpRequestDto: {
      /**
       * @description User email address
       * @example user@example.com
       */
      email: string;
      /**
       * @description User password
       * @example password123
       */
      password: string;
      /**
       * @description User full name
       * @example John Doe
       */
      name: string;
      /**
       * @description User slug
       * @example johndoe
       */
      slug?: string;
    };
    AuthResponseDto: {
      /**
       * @description Access token for authenticated requests
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
       */
      accessToken: string;
    };
    LoginRequestDto: {
      /**
       * @description User email address
       * @example user@example.com
       */
      email: string;
      /**
       * @description User password
       * @example password123
       */
      password: string;
    };
    ScheduleResponseDto: Record<string, never>;
    ScheduleDayRequestDto: {
      /**
       * @description The start time of a work day
       * @example 540
       */
      startTime: number;
      /**
       * @description The end time of a work day
       * @example 1040
       */
      endTime: number;
      /**
       * @description The index of the day in a week. Start from Sunday
       * @example 1
       */
      weekday: number;
    };
    ScheduleBatchRequestDto: {
      /** @description An array of weekdays */
      items: components['schemas']['ScheduleDayRequestDto'][];
    };
    SlotResponseDto: Record<string, never>;
    CreateBookingRequestDto: {
      /** @example johndoe */
      slug: string;
      /**
       * Format: date
       * @example 2026-09-04
       */
      date: string;
      /** @example 540 */
      startTime: number;
      /** @example 570 */
      endTime: number;
      /** @example John Doe */
      clientName: string;
      /**
       * @description Client email
       * @example user@example.com
       */
      clientEmail?: string;
      /**
       * @description Client phone number
       * @example +380981112233
       */
      clientPhone?: string;
    };
    CreateBookingResponseDto: {
      /**
       * @description Booking ID
       * @example asdfko32t2kl45tgasf
       */
      id: string;
      /**
       * Format: date-time
       * @description Booking start time
       * @example 2026-09-08T09:00:00.000Z
       */
      startTime: string;
      /**
       * Format: date-time
       * @description Booking end time
       * @example 2026-09-08T09:30:00.000Z
       */
      endTime: string;
      /**
       * @description Booking client name
       * @example John Doe
       */
      clientName: string;
    };
    /**
     * @description Booking status
     * @enum {string}
     */
    BookingStatus: 'ACTIVE' | 'CANCELLED';
    BookingItemResponseDto: {
      /**
       * @description Booking id
       * @example o4BK3P86xBab0hw1KTOG3
       */
      id: string;
      /**
       * @description Master id
       * @example o4BK3P86xBab0hw1KTOG3
       */
      userId: string;
      /**
       * Format: date-time
       * @description Booking end time
       * @example 2026-09-08T09:30:00.000Z
       */
      startTime: string;
      /**
       * Format: date-time
       * @description Booking end time
       * @example 2026-09-08T09:30:00.000Z
       */
      endTime: string;
      /**
       * @description Booking status
       * @example ACTIVE
       */
      status: components['schemas']['BookingStatus'];
      /**
       * @description Client name
       * @example John Doe
       */
      clientName: string;
      /**
       * @description Client email
       * @example example@example.com
       */
      clientEmail: string;
      /**
       * @description Client phone number
       * @example +380981112233
       */
      clientPhone: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type UserResponseDto = components['schemas']['UserResponseDto'];
export type SignUpRequestDto = components['schemas']['SignUpRequestDto'];
export type AuthResponseDto = components['schemas']['AuthResponseDto'];
export type LoginRequestDto = components['schemas']['LoginRequestDto'];
export type ScheduleResponseDto = components['schemas']['ScheduleResponseDto'];
export type ScheduleDayRequestDto = components['schemas']['ScheduleDayRequestDto'];
export type ScheduleBatchRequestDto = components['schemas']['ScheduleBatchRequestDto'];
export type SlotResponseDto = components['schemas']['SlotResponseDto'];
export type CreateBookingRequestDto = components['schemas']['CreateBookingRequestDto'];
export type CreateBookingResponseDto = components['schemas']['CreateBookingResponseDto'];
export type BookingStatus = components['schemas']['BookingStatus'];
export type BookingItemResponseDto = components['schemas']['BookingItemResponseDto'];
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get current user */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
    };
  };
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignUpRequestDto'];
      };
    };
    responses: {
      /** @description User registered successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequestDto'];
      };
    };
    responses: {
      /** @description User logged in successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tokens pair refreshed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logout successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ScheduleController_getUserSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Master week schedule */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScheduleResponseDto'][];
        };
      };
    };
  };
  ScheduleController_updateUserSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScheduleBatchRequestDto'];
      };
    };
    responses: {
      /** @description Schedule updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScheduleResponseDto'][];
        };
      };
    };
  };
  BookingsController_getSlots: {
    parameters: {
      query: {
        slug: string;
        date: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns response with selected date and free slots */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SlotResponseDto'];
        };
      };
    };
  };
  BookingsController_createBooking: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateBookingRequestDto'];
      };
    };
    responses: {
      /** Booking was created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreateBookingResponseDto'];
        };
      };
    };
  };
  BookingsController_getUserBookings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns a list of bookings for the current client */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BookingItemResponseDto'][];
        };
      };
    };
  };
  BookingsController_cancelBooking: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Booking cancelled successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
